version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: roy
      MONGO_INITDB_ROOT_PASSWORD: B0721138
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
  adminmongo:
    image: mrvautin/adminmongo
    links: ['mongo:mongo']
    ports:
      - "127.0.0.1:1234:1234"
    environment:
      - HOST=0.0.0.0